services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: sidequestdb
    volumes:
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    - ./mongo_data:/data/db

  # server:
  #   image: side-quest-backend
  #   environment:
  #     - SECRET=SuperSecretStringOMG
  #     - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/sidequestdb
  #   ports:
  #     - 3000:4000